# Generated by Django 5.0.3 on 2024-08-28 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceta', '0004_remove_client_email_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email_client',
            field=models.EmailField(max_length=254, null=True, unique=True, verbose_name='Email'),
        ),
    ]
